"""
load_db.py

Loads the CSVs generated by data_generator.py (./data/*.csv) into a SQLite
database (./aml.db). Creates the base tables plus one convenience view,
vw_transactions, which joins transactions -> accounts -> customers ->
jurisdictions into a single denormalized row.

vw_transactions is the "clean" surface the SQL detectors in /detections
query against, so each detection file can stay pure SQL with no repeated
join boilerplate.

Run:
    python load_db.py
"""

import csv
import sqlite3
from pathlib import Path

DATA_DIR = Path(__file__).parent / "data"
DB_PATH = Path(__file__).parent / "aml.db"

SCHEMA_SQL = """
DROP VIEW IF EXISTS vw_transactions;
DROP TABLE IF EXISTS transactions;
DROP TABLE IF EXISTS accounts;
DROP TABLE IF EXISTS customers;
DROP TABLE IF EXISTS jurisdictions;

CREATE TABLE jurisdictions (
    jurisdiction_code   TEXT PRIMARY KEY,
    jurisdiction_name   TEXT NOT NULL,
    risk_level          TEXT NOT NULL CHECK (risk_level IN ('LOW', 'HIGH'))
);

CREATE TABLE customers (
    customer_id         TEXT PRIMARY KEY,
    full_name           TEXT NOT NULL,
    dob                 TEXT NOT NULL,
    home_jurisdiction   TEXT NOT NULL REFERENCES jurisdictions(jurisdiction_code),
    customer_since      TEXT NOT NULL
);

CREATE TABLE accounts (
    account_id          TEXT PRIMARY KEY,
    customer_id         TEXT NOT NULL REFERENCES customers(customer_id),
    account_type        TEXT NOT NULL CHECK (account_type IN ('checking', 'savings', 'business')),
    open_date            TEXT NOT NULL
);

CREATE TABLE transactions (
    transaction_id              TEXT PRIMARY KEY,
    account_id                  TEXT NOT NULL REFERENCES accounts(account_id),
    customer_id                 TEXT NOT NULL REFERENCES customers(customer_id),
    timestamp                   TEXT NOT NULL,
    amount                      REAL NOT NULL,
    direction                   TEXT NOT NULL CHECK (direction IN ('credit', 'debit')),
    counterparty                TEXT NOT NULL,
    counterparty_jurisdiction   TEXT NOT NULL REFERENCES jurisdictions(jurisdiction_code),
    channel                     TEXT NOT NULL
);

CREATE INDEX idx_transactions_customer_ts ON transactions(customer_id, timestamp);
CREATE INDEX idx_transactions_account_ts  ON transactions(account_id, timestamp);
CREATE INDEX idx_transactions_jurisdiction ON transactions(counterparty_jurisdiction);

-- Denormalized view: this is what the /detections/*.sql files query.
CREATE VIEW vw_transactions AS
SELECT
    t.transaction_id,
    t.account_id,
    a.account_type,
    t.customer_id,
    c.full_name                    AS customer_name,
    c.home_jurisdiction,
    t.timestamp,
    t.amount,
    t.direction,
    t.counterparty,
    t.counterparty_jurisdiction,
    j.risk_level                   AS counterparty_risk_level,
    t.channel
FROM transactions t
JOIN accounts a     ON a.account_id = t.account_id
JOIN customers c    ON c.customer_id = t.customer_id
JOIN jurisdictions j ON j.jurisdiction_code = t.counterparty_jurisdiction;
"""


def read_csv_rows(filename):
    path = DATA_DIR / filename
    with open(path, newline="") as f:
        return list(csv.DictReader(f))


def load_jurisdictions(conn):
    rows = read_csv_rows("jurisdictions.csv")
    conn.executemany(
        "INSERT INTO jurisdictions (jurisdiction_code, jurisdiction_name, risk_level) VALUES (:jurisdiction_code, :jurisdiction_name, :risk_level)",
        rows,
    )
    return len(rows)


def load_customers(conn):
    rows = read_csv_rows("customers.csv")
    conn.executemany(
        "INSERT INTO customers (customer_id, full_name, dob, home_jurisdiction, customer_since) "
        "VALUES (:customer_id, :full_name, :dob, :home_jurisdiction, :customer_since)",
        rows,
    )
    return len(rows)


def load_accounts(conn):
    rows = read_csv_rows("accounts.csv")
    conn.executemany(
        "INSERT INTO accounts (account_id, customer_id, account_type, open_date) "
        "VALUES (:account_id, :customer_id, :account_type, :open_date)",
        rows,
    )
    return len(rows)


def load_transactions(conn):
    rows = read_csv_rows("transactions.csv")
    for row in rows:
        row["amount"] = float(row["amount"])
    conn.executemany(
        "INSERT INTO transactions "
        "(transaction_id, account_id, customer_id, timestamp, amount, direction, counterparty, counterparty_jurisdiction, channel) "
        "VALUES (:transaction_id, :account_id, :customer_id, :timestamp, :amount, :direction, :counterparty, :counterparty_jurisdiction, :channel)",
        rows,
    )
    return len(rows)


def main():
    if DB_PATH.exists():
        DB_PATH.unlink()

    conn = sqlite3.connect(DB_PATH)
    conn.execute("PRAGMA foreign_keys = ON;")
    conn.executescript(SCHEMA_SQL)

    n_jurisdictions = load_jurisdictions(conn)
    n_customers = load_customers(conn)
    n_accounts = load_accounts(conn)
    n_transactions = load_transactions(conn)

    conn.commit()
    conn.close()

    print(f"Loaded into {DB_PATH}:")
    print(f"  jurisdictions: {n_jurisdictions}")
    print(f"  customers:     {n_customers}")
    print(f"  accounts:      {n_accounts}")
    print(f"  transactions:  {n_transactions}")
    print("View vw_transactions created for use by /detections/*.sql")


if __name__ == "__main__":
    main()
